### ISSUE TITLE
gearman:worker:list returns exception

### ISSUE THREAD

**Issue by bmeynell** [mmoreram/GearmanBundle#16]
The following command returns an exception when configuration is different than the test worker. I'm assuming it is a problem with the autoloading.

```
php app/console gearman:worker:list
```

Results in:

```
Fatal error: Class 'PHPUnit_Framework_TestCase' not found in /var/www/project/src/vendor/symfony/src/Symfony/Bundle/FrameworkBundle/Test/WebTestCase.php on line 24
```

For example, in `app/config/gearman/dev.yml` the following outputs worker information:

``` yaml
bundles:
    GearmanBundle:                                                                    
        namespace: Mmoreramerino\GearmanBundle                          
        active: true
```

However, putting the same `testWorker.php` in a different bundle under a `Workers` folder, the `gearman:worker:list` command produces the exception. For example:

``` yaml
bundles:
    GearmanBundle:                                                                    
        namespace: Mmoreramerino\GearmanBundle                          
        active: false
    ProjectBundle:                                                                 
        namespace: MyProject\Bundle\MyBundle                 
        active: true
```
