### ISSUE TITLE
Servers config is not used. Always connecting to localhost

### ISSUE THREAD

**Issue by darklow** [mmoreram/GearmanBundle#23]
Could anyone please test connection to different gearman server rather than default?
For example i have config:

```
defaults:
    servers:
        cache:
            hostname: 192.168.0.223
            port: 4730
```

But client always tries to connect 127.0.0.1 

```
$gearman = $this->getContainer()->get('gearman');
```

I know the problem is not in the config itself, because when i dump:

```
$gearman->getSettings()
```

I got all the server config correctly, so right now my temporary fix i could think of to get things work is:

```
$gearman = $this->getContainer()->get('gearman');
$settings = $gearman->getSettings()['defaults']['servers']['cache'];
$gearman->setServer($settings['hostname']);
$result = $gearman->doBackgroundJob....
```

Thank you.
