### ISSUE TITLE
Unrecognized options "namespace" under "gearman.bundles.***"

### ISSUE THREAD

**Issue by hemantthorat** [mmoreram/GearmanBundle#40]
Hi,
I have update my composer to your new branch.
After making following changes to  configuration file,

```
gearman:
    # Bundles will parsed searching workers
    bundles:
    # Name of bundle
    SiteBundle:

        # Bundle namespace
        namespace: Stockopedia\SiteBundle
```

When I tried to update composer , getting following error,

Installing mmoreram/gearman-bundle (dev-master 4fcd8f1)
    Cloning 4fcd8f1c9a9ede2d412e02471ad9faa8c31dce0e

Writing lock file
Generating autoload files
Updating the "app/config/parameters.yml" file.

  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized options "namespace" under "gearman.bundles.SiteBundle"

Kindly suggest solution, if any.
